Format:
  Namespace: File
  Usings:
    Sort: Alphabetical
    RemoveUnused: false
  Variables:
    UseVar: Never
  Collections:
    PreferExpression: true
  Initializers:
    Object: MultiLine
    Collection: SingleLine
    AnonymousType: MultiLine
  Ternary:
    Style: MultiLine
  Spacing:
    EmptyLineBeforeControlFlow: true
    EmptyLineAfterControlFlow: true
  Modifiers:
    MakeStaticWhenPossible: true
  Optimization:
    PreferLengthCountOverAny: true

Include:
  - "Styly/**/*.cs"
  - "Styly.Tests/**/*.cs"
Exclude:
  - "**/obj/**"